#!/usr/bin/env php
<?php

// Intercept "serve" command: bypass artisan's broken Symfony Process
// (doesn't handle spaces in paths, child processes don't inherit -c flag)
// $args = $argv ?? $_SERVER['argv'] ?? [];
// if (count($args) >= 2 && $args[1] === 'serve') {
//     $port = '8000';
//     $host = '127.0.0.1';
//     $len = count($args);
//     for ($i = 2; $i < $len; $i++) {
//         if ($args[$i] === '--port' && $i + 1 < $len) { $port = $args[$i + 1]; $i++; }
//         elseif (str_starts_with($args[$i], '--port=')) { $port = substr($args[$i], 7); }
//         elseif ($args[$i] === '--host' && $i + 1 < $len) { $host = $args[$i + 1]; $i++; }
//         elseif (str_starts_with($args[$i], '--host=')) { $host = substr($args[$i], 7); }
//     }
//     $root = __DIR__;
//     $php = PHP_BINARY;
//     $ini = $root . DIRECTORY_SEPARATOR . 'php_custom.ini';
//     $doc = $root . DIRECTORY_SEPARATOR . 'public';
//     $router = $root . DIRECTORY_SEPARATOR . 'server.php';
//     $cmd = sprintf(
//         '"%s" -c "%s" -S %s:%s -t "%s" "%s"',
//         $php, $ini, $host, $port, $doc, $router
//     );
//     echo "\033[32mEventOS Dev Server:\033[0m http://{$host}:{$port}\n";
//     echo "\033[33mPress Ctrl+C to stop.\033[0m\n\n";
//     passthru($cmd, $exitCode);
//     exit($exitCode);
// }

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput,
);

$exitCode = $kernel->terminate($input, $status);

exit($exitCode);
